version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: laravel-app
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - XDEBUG_CONFIG=remote_enable=1 remote_autostart=1
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "4306:3306"

volumes:
  dbdata:
